
##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  king配置  ###################
king:
  swagger-open: true #是否开启swagger (true/false)
  kaptcha-open: true #是否开启登录时验证码 (true/false)
  #file-upload-path: d:/tmp  #文件上传目录(不配置的话为java.io.tmpdir目录)
  muti-datasource-open: false #是否开启多数据源(true/false)
  spring-session-open: false #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800 #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900 #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  server-private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAIsSB7RDMNzg/9CRmHarO9Z9fvjAx0zBGujxzXlH7Jbb3tucQHy3OoeOXRHGd2bNcYlVkbuIlqUvZW5P/rr4x8mZKuDqUtsbIj17vboWpKUvg5RGLglpe9PaOhIy5wKNcrfUfBm4OzLFF+z5Xg5lz8MDkPwzEjppx+g+5g3Nin/XAgMBAAECgYAYpSNUYKviGMV80rBwJzw9cJP1xUQMaBQ6v88n9QUKXwCJbpFHCLmImEQKCF/UigfazJ083KHFuDaDbA26WKge3nkCCIEa5MbLQUuKVPTqmC3ue12vkZd1GU8HVQwwGpE2BSsanMz7IXKRGKip8gDzYxxfTtI+bixeQUW+1AyyEQJBAPeILxfhc0PtmmNwEiQov+e1dftNv/FUaEcQD93engZWfgrUZwrJYxzyskZudUGVmT14GzxDb1/TBHZgbAC11eMCQQCP0/heTHnUb2a9sRNIVWAe1r6OUnIhoxtS4sEKfv/SVXqVemI5mVAFp+JqEbTbKLgT9MOfFszLB7RbJdVth7B9AkEAlKWXgkPFMHmzSRu4CTbfZ4o1O6DJL2d854/ht19EjpHKRz6eUn/1oSCtplYW3De2Oo+x61Kjw2u5Nk1ZDmQj+QJALg3ItKE2TYCSXGEr9Hhp+9X1VGsv4ndw01yKRYse7UGzq9NxSlI+HmGAjUg4Kgji0HkKfpF1Z/mClcEKkzTknQJBALliApl2YwlCntsX3+myL9lwZMYANZkdyJUEO8PbeOzGVlRA70e+aW6QLH2eWbea5Fw+pzn9eACUu7KU7Gw4WJM=
  client-public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLEge0QzDc4P/QkZh2qzvWfX74wMdMwRro8c15R+yW297bnEB8tzqHjl0RxndmzXGJVZG7iJalL2VuT/66+MfJmSrg6lLbGyI9e726FqSlL4OURi4JaXvT2joSMucCjXK31HwZuDsyxRfs+V4OZc/DA5D8MxI6acfoPuYNzYp/1wIDAQAB
 
###################  项目启动端口  ###################
server:
  port: 8099

###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件bfuser目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


###################  spring配置  ###################
spring:
  redis:
    host: localhost
    port: 6379
    password:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/view
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  devtools:
    restart:
      enabled: false #是否开启开发者工具（true/false）
      additional-paths: src/main/java
      exclude: static/**,WEB-INF/view/**
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  mail:
    host: smtp.163.com
    username: m_ljf4@163.com
    password: kg123456
  quartz:
    cron-email-message-send: 0/10 * * * * ?

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/kingoin/king/**/mapping/*.xml
  typeAliasesPackage: com.kingoin.king.modular.system.model
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

---

##########################################################
###################  开发环境的profile  useUnicode=true&###################
##########################################################
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://111.229.181.74:3306/z_cai_dev?autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Lz_20200304
    db-name: wuyun
    filters: log4j,wall,mergeStat
---
##########################################################
###################  正式环境的profile  ###################
##########################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://111.229.181.74:3306/zj_dev_all?autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Lz_20200304
    db-name: wuyun
    filters: log4j,wall,mergeStat
logging:
  level.root: warn
  path: logs/
  file: king.log
---

#flowable数据源和多数据源配置
king:
  flowable:
    datasource:
      url: jdbc:mysql://134.175.84.161:3306/cai?autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root123456
  muti-datasource:
    default-dataSource-name: dataSourceGuns #默认的数据源名称
    url: jdbc:mysql://134.175.84.161:3306/z_cai_dev?autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root123456
    
logging:
  level.bfuser: info
  level.com.kingoin: debug
  path: logs/
  file: king.log

---



